ui:
  tag: "23"
catalog:
  tag: "23"
catalog_db:
  tag: "23"
checkout:
  tag: "23"
checkout_db:
  tag: "23"
orders:
  tag: "23"
orders_db:
  tag: "23"
orders_db_rabbitmq:
  tag: "23"
cart:
  tag: "23"
cart_dynamodb:
  tag: "23"
assets:
  tag: "23"
