# Default values for do_it_yourself.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ui:
  tag: "8e6b2e"
catalog:
  tag: "8e6b2e"
catalog-db:
  tag: "8e6b2e"
checkout:
  tag: "8e6b2e"
checkout-db:
  tag: "8e6b2e"
orders:
  tag: "8e6b2e"
orders-db:
  tag: "8e6b2e"
orders-db-rabbitmq:
  tag: "8e6b2e"
cart:
  tag: "8e6b2e"
cart-dynamodb:
  tag: "8e6b2e"
assets:
  tag: "8e6b2e"
