# Default values for do_it_yourself.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ui:
  tag: "4ab88c"
catalog:
  tag: "4ab88c"
catalog-db:
  tag: "4ab88c"
checkout:
  tag: "4ab88c"
checkout-db:
  tag: "4ab88c"
orders:
  tag: "4ab88c"
orders-db:
  tag: "4ab88c"
orders-db-rabbitmq:
  tag: "4ab88c"
cart:
  tag: "4ab88c"
cart-dynamodb:
  tag: "4ab88c"
assets:
  tag: "4ab88c"
