# Default values for do_it_yourself.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ui:
  tag: "17"
catalog:
  tag: "17"
catalog-db:
  tag: "17"
checkout:
  tag: "17"
checkout-db:
  tag: "17"
orders:
  tag: "17"
orders-db:
  tag: "17"
orders-db-rabbitmq:
  tag: "17"
cart:
  tag: "17"
cart-dynamodb:
  tag: "17"
assets:
  tag: "17"