apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: revive-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cyprientemateu/cyprien-ecommerce-project-automation.git
    targetRevision: main
    path: chart
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: revive-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
